pve_api_token: ENC[AES256_GCM,data:Gyab+W0PI0s+OoKspSItHO0/5S4YhMmQ6kT/Z034jZ3urjwCv/wNs3P1omIXa6GrUBrshGJ08N+R3Ng=,iv:N5QtzS6M7EhD94dUNlENy1I6f8z4uEop32uk4qFJjfo=,tag:Fv16PN3iddVXwKPSqoxTvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwV0kyNERnTWdsbnpTSGVE
            cjFzRmh5QVpZNzRmMjdhOEpuZmZKMlhSV3pVCmdKM0drZFhocEQ3blNQeEdsMzFZ
            ZVRMTDdidjFzVTJuWlJDRlJTd2dudUEKLS0tIE11S3RYVzNxbTVJZUk5cWVWWW9X
            cERaS1JXSll1bUpBZTVVWlF4OHpZdEEKiETeXV2uSO7W6POrHcRsFhjXOLP5r9DV
            m5OX0k9HZOAnohphb4s0D4m0AA7Z+s7yFDNj/fT1uIg9zjOhPlEkBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n60xeumad6dxu59864v3dydp2jxj0nerlvtqf3y3gaaqh3ffnv5s7l39qn
    lastmodified: "2026-05-20T22:52:32Z"
    mac: ENC[AES256_GCM,data:3i3+jZv0mTbGPLvryNv0x2CLBAn2z3kOKQjHs8rrKOG/NRW7qaSgB1ehJNtk27WGPp0Ow2xWhglnY4/vkGl6+uZ+Luo6GxDXhQITvwoMHmNFgX/pnhe38KfnSet0iM2beau2YRgZPz4UgL2HqgtUu4+YvSJzguSs+8xTtVSlmDo=,iv:7wZC3OTl2z2PPrmnC+VI+ktxWCtNXiYFXg7RfbcRCVE=,tag:wENIq0MHV9f86wgkf33jkQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
