pve_api_token: ENC[AES256_GCM,data:Gyab+W0PI0s+OoKspSItHO0/5S4YhMmQ6kT/Z034jZ3urjwCv/wNs3P1omIXa6GrUBrshGJ08N+R3Ng=,iv:N5QtzS6M7EhD94dUNlENy1I6f8z4uEop32uk4qFJjfo=,tag:Fv16PN3iddVXwKPSqoxTvw==,type:str]
pbs_main_password: ENC[AES256_GCM,data:g6C5EjFNFoPhGescp2p2IhnR56VBpHTYMOe59f50S4kTwl10,iv:P5Sp1M13bFTOY6HR8rHHVeqOkwxkSaqv0OLp4VOaIlw=,tag:rWdHA+Erssqu7qXJGJ9Vbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwV0kyNERnTWdsbnpTSGVE
            cjFzRmh5QVpZNzRmMjdhOEpuZmZKMlhSV3pVCmdKM0drZFhocEQ3blNQeEdsMzFZ
            ZVRMTDdidjFzVTJuWlJDRlJTd2dudUEKLS0tIE11S3RYVzNxbTVJZUk5cWVWWW9X
            cERaS1JXSll1bUpBZTVVWlF4OHpZdEEKiETeXV2uSO7W6POrHcRsFhjXOLP5r9DV
            m5OX0k9HZOAnohphb4s0D4m0AA7Z+s7yFDNj/fT1uIg9zjOhPlEkBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n60xeumad6dxu59864v3dydp2jxj0nerlvtqf3y3gaaqh3ffnv5s7l39qn
    lastmodified: "2026-05-21T01:02:09Z"
    mac: ENC[AES256_GCM,data:3Vf6x7pu9LFxvbk8itmn2mv+3HaqAeRq5G+w1lmH9LtUvpSNqd+Pyr0si5wMFV+CGEmvt0dFuwZQINuCKPLs25T+OSFX90xBaUM0jKIDn2kjuaUM50ou0to0d1QdR1IFwMpYoMgYl99lk53ChtW9AWcVipnw/M6wGU5p0jvoagw=,iv:tU/N25HX6d9m/vas9icGdX7+1Yv+cZlnQ9h5sz682nc=,tag:mjBjbED+wpffSlHEBbZRXg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
