#ENC[AES256_GCM,data:j1Fpy2h4vvlsunqbt1SH5NnecGW700cYFD23v838+wFix42dAy+2BIaPhB9cuTKFFfUvpOE6Q4itJqNpDc048QAebWY=,iv:hKRJbCJmMLvaMowV8S2UJszBXXmXrWP0+E2u2JHPPuo=,tag:auy49wgkeSLC/juK+XrW0Q==,type:comment]
#ENC[AES256_GCM,data:t0eDL4hAt+XmCqfLfpaGnojRE+CI+L/S1nS3RCbc1UlGoyTvz3hQRn70UQi80TPpxD8=,iv:nLToH7LRvot7+oqNKsbpHgYUwoLQlW/XSjKrWmDIyAI=,tag:2jeC45sya82S2Bb8V1FYww==,type:comment]
#ENC[AES256_GCM,data:9KBlFjk7jnyudVoRlzD9MTByjwIE6csjPFb2tqViTZuoZ255yu9tnVQnYuGuIiuI170XaSgKRe45f6LaXOtjqpO8RNjHt2qG8UK59w==,iv:7AgrDV+sCdNbwb0VaXVtB7vLEqt1wp/3poHiGcJQfFs=,tag:2d84g2s+39POcSsMtWiKCQ==,type:comment]
alloy_remote_write_username: ENC[AES256_GCM,data:QB4Yt/k=,iv:9L47e7e29UR0B+laKJQPo+01ej3w6+M+jr/tPLl++yU=,tag:LigTrv+NvQgdmxr/trKSqA==,type:str]
alloy_remote_write_password: ENC[AES256_GCM,data:O0zavKqDsZinaZddjoPIJnI0p9kYRmVHq4NtBxHHbo8=,iv:5Lu9PTeZD78dPHScJBwx5XkZglaYNQYe0zFCPaIsLBw=,tag:dWm58ND/3I+9wV3LSA39cA==,type:str]
loki_basic_auth_password: ENC[AES256_GCM,data:lXRFA/6ODwvRSDeX1IAGGMgW0yFljEtc,iv:riRH32+pVOYlErrXYkp6A6N4ezlSOJHo0bWfMHps1nQ=,tag:fZtSC3dbGPFffRP4LRIgSA==,type:str]
sops:
    age:
        - recipient: age1n60xeumad6dxu59864v3dydp2jxj0nerlvtqf3y3gaaqh3ffnv5s7l39qn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFN0lUK0RKVkIyeW1yU245
            Tmp3UWtSemx4aDROeHJ0dis5WXg0K1dLem5BCnVrQ0FzdndRSEd4T1JKbzRjK1dV
            RW15aW1tNzZ1ZE5TNUF1YnhDUXBrWVUKLS0tIGpmV2lRSW9JOUZBKzhrRXFXTzZ0
            SWFXRGMvbXhkdHY4d0V5TndZQ3N1N3MKhDgDQXvIO4GVMh3dX3fR19FSSr8npRuc
            fgn0j5FOzYdbOWZkFaBdVTIJJkm26T7jhP98LimPlYD0S8ZpjtC39Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T21:02:08Z"
    mac: ENC[AES256_GCM,data:Fd5aeWQ/eOuOIGs+lvQ8ltsWnIci4gVCjF53VIRYftq9IZrP/4WdRP9CJW5YsCDhNwk9uMXiux1yaLFoYTdKZqnPrHgUqNZtb/UtHpA13037DiX87XdTiCwa+sB20nllX5RIoY1xnNPgJzjb04la1a5mdmU4Qy4GpDMy2p3Wv60=,iv:54A25sCE5uMmOVmRasReSH79ZvNFoywO1dsVb8uuhA0=,tag:xKgo9iAchQ8QWRPtHN0l8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
