#ENC[AES256_GCM,data:j1Fpy2h4vvlsunqbt1SH5NnecGW700cYFD23v838+wFix42dAy+2BIaPhB9cuTKFFfUvpOE6Q4itJqNpDc048QAebWY=,iv:hKRJbCJmMLvaMowV8S2UJszBXXmXrWP0+E2u2JHPPuo=,tag:auy49wgkeSLC/juK+XrW0Q==,type:comment]
#ENC[AES256_GCM,data:t0eDL4hAt+XmCqfLfpaGnojRE+CI+L/S1nS3RCbc1UlGoyTvz3hQRn70UQi80TPpxD8=,iv:nLToH7LRvot7+oqNKsbpHgYUwoLQlW/XSjKrWmDIyAI=,tag:2jeC45sya82S2Bb8V1FYww==,type:comment]
#ENC[AES256_GCM,data:9KBlFjk7jnyudVoRlzD9MTByjwIE6csjPFb2tqViTZuoZ255yu9tnVQnYuGuIiuI170XaSgKRe45f6LaXOtjqpO8RNjHt2qG8UK59w==,iv:7AgrDV+sCdNbwb0VaXVtB7vLEqt1wp/3poHiGcJQfFs=,tag:2d84g2s+39POcSsMtWiKCQ==,type:comment]
alloy_remote_write_username: ENC[AES256_GCM,data:QB4Yt/k=,iv:9L47e7e29UR0B+laKJQPo+01ej3w6+M+jr/tPLl++yU=,tag:LigTrv+NvQgdmxr/trKSqA==,type:str]
alloy_remote_write_password: ENC[AES256_GCM,data:O0zavKqDsZinaZddjoPIJnI0p9kYRmVHq4NtBxHHbo8=,iv:5Lu9PTeZD78dPHScJBwx5XkZglaYNQYe0zFCPaIsLBw=,tag:dWm58ND/3I+9wV3LSA39cA==,type:str]
sops:
    age:
        - recipient: age1n60xeumad6dxu59864v3dydp2jxj0nerlvtqf3y3gaaqh3ffnv5s7l39qn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFN0lUK0RKVkIyeW1yU245
            Tmp3UWtSemx4aDROeHJ0dis5WXg0K1dLem5BCnVrQ0FzdndRSEd4T1JKbzRjK1dV
            RW15aW1tNzZ1ZE5TNUF1YnhDUXBrWVUKLS0tIGpmV2lRSW9JOUZBKzhrRXFXTzZ0
            SWFXRGMvbXhkdHY4d0V5TndZQ3N1N3MKhDgDQXvIO4GVMh3dX3fR19FSSr8npRuc
            fgn0j5FOzYdbOWZkFaBdVTIJJkm26T7jhP98LimPlYD0S8ZpjtC39Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:04:26Z"
    mac: ENC[AES256_GCM,data:0mAeDA/J3XjI1ykAXwOdX8NkS9OzHvWypD2P4lAA9gwzGXCLzAiBE765gx8ovngJXhBHiS4H9Pzre+t1Z5DEgg0QP+2u/ygZYPKsCZI7J4Eyp/NN9eiUo2tnbKyRt5cT/LMP1ioWipe0HcRsUzEqH8IRwhunR4QYSzjd0471zzw=,iv:JHPG+Lh5PTwyE4BncDpEQgUd/vyEy9Bz9yVVUsALLG4=,tag:0cy1Ogm9fffuwEUHZYtOpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
