apiVersion: v1
kind: Secret
metadata:
    name: sops-test
    namespace: default
type: Opaque
stringData:
    message: ENC[AES256_GCM,data:aZ0nK//9fvglz7X59qbl,iv:zpRZ0g3tAkN7p1c8GIiOe7YYL/uWeEAvqXAADjsI45A=,tag:Bah495OZJ/9PbVTxwmQhTA==,type:str]
sops:
    age:
        - recipient: age1n60xeumad6dxu59864v3dydp2jxj0nerlvtqf3y3gaaqh3ffnv5s7l39qn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdHVPSVY1N25DWHZQNEkw
            QW5SZTdTYXZqUmM5UnJTQTk2RWRJNDlIczBZCmNaUVhvZzEzNHBtTEhEOXdLbUtR
            VTkwQ2RQUDRHS0RRT096d1NqTzF5ZFkKLS0tIEZYY0NwVC9IRHJsRVAxVUE1ZVEz
            eStjaWRmalZ3ajdSenlMYzR3ZzJJU0kKk8+ZCUNcc3BhB+M6CXsHltaYG4TuWH8n
            2OmKQe4wH3yTOCmFnDNwS1SytVuLIItlyQtkA7lgJb+IDvIW+3TjFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T22:06:16Z"
    mac: ENC[AES256_GCM,data:2vLzsugZjyyCizYdWbMch5shBKWj4/zHmSak1iC7IxAbGzY2taVhSBggp7ifgD/Rb+2Dr8hBBe9AhbskUz2LgPYHkUP6Iu7FncJm+j1f8vxrVlddp0qQxJR8q5JkfikiS8VB5itxrXJsAZI991enYlDHvzuw7B27kn7kQx1lH4A=,iv:e6iWZu+vzqPkt4izI6/4wgDV/kXN2sDyoULr3IiyzNA=,tag:hRGtQicG4r64cNWYUklPpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
