apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - postgres-podmonitor.yaml
  - library-pvc.yaml
  - bulk-photos-pv.yaml
  - bulk-media-pv.yaml
  - tirion-ca-configmap.yaml
  - immich.yaml
  - immich-route.yaml
