apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:HaqAHXdwR+zZrvCMp6JYgQ2mmXsqHdS/z8hiD+y+2zAqdTBb8mVswwibmMj0Nh1rf3K5nNWpMdebL3OTRab+VpAlaXECIyL89g6YYkBsBgw=,iv:gHlrPUaDsgCKP/+0oB/ZOW+MFvU4LZ/mrnkmGVeGBiM=,tag:Z28LkbsCRZAsCxz46SZM5A==,type:str]
    bootstrap_password: ENC[AES256_GCM,data:O+iTnVAhr4LgXpHWwv3UEp9tmsmD8DWq7c0l0UYeNQ==,iv:7FMGMCXo3qRPd5ptfrQhUDwbG2HetA9XA3rJG0ZjyyI=,tag:ZUAw5fuf95RUQ8LrUmdI3w==,type:str]
    bootstrap_token: ENC[AES256_GCM,data:+QXoDrXlMfAswldZm3IWswHe+8sjH10O27RO820FWlrOCjhumJd7NcPgpPZYkhuGtgR3GfDwbomIxdooklRH6Q==,iv:+2LaB8zeMSyies6gmxshriemoEyVjN2CV+xKqI6cFO4=,tag:JQVqP5e7SCZDZ8izz9i5Fw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUnBiM2pNVHoyWGI2Z1M0
            bmhHd2J2a2R2czBiTWwvc1Jzc05XTjVqbHpRCkFrcG5nYW5lOHB2WVBybmhtcXdY
            dzhOczdkN2kzc3JlWHZVd1ljaytvNG8KLS0tIGo4TkFpWXZGOXAyQmRXNXdPakJY
            dUJuZk8zL0U0M0Q4QjBCUStjc0o4cnMKqxqxxZKh/LnYDUd/iLcNSUiqcn+XIxcI
            ENvoITKEoadr6IA7XQbbZnythXGQQ9CV1Rjg2rHPIzxJbrQVqwBvuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n60xeumad6dxu59864v3dydp2jxj0nerlvtqf3y3gaaqh3ffnv5s7l39qn
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T05:30:51Z"
    mac: ENC[AES256_GCM,data:gHxajkag7lVgClDPkQfX9fVCnAwdLmZegbDiRyKWUmlwnT5OoP7Z6oW5xQBVqMORbOtT//W9DmS9IPWufx9xPBrljDwyDTdJJEvsmMvhxopcj0DCTGt2QgQcSL+/0rFag2dejvJVQgs4cJqUU8FNRKOHIEwmUMi0EkapjgjLRX8=,iv:tPQls6y+qLn7XkZCZwix9EYdO9COwlrndjEHaFY2ics=,tag:6lEcV1FcOTP4q3ughpgzoQ==,type:str]
    version: 3.13.1
