apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - postgres-podmonitor.yaml
  - valkey.yaml
  - authentik-secret.yaml
  - authentik.yaml
  - authentik-route.yaml
