#ENC[AES256_GCM,data:GZvK/5ZT/etVuu3zUcVsDaezipcJ9+GiaQiqs2cSiqLWliEl6T8NEkHzsJCFS6SeSkwUBkT0lvA3ySMy7EWr+aK6SVDCh50g+A==,iv:ni7d8XynSEiKbxKjjIututVMwG2M7fPokG6jhUZzJzU=,tag:lGt0agPtT2acOSK1rqfg3w==,type:comment]
#ENC[AES256_GCM,data:nS6SOQodKyLe0nkgBtt5VZ6iW4bsVpy7YPd/GU7lZBoxlj3Y6hzFlHIFOm6QD0mzZgU=,iv:RSFikE0VyNsIowhJ/+jPjK8WY0KSpP/8GSHNuRkmMDg=,tag:nOXCtdU5AzZ3xRkEFNwUiA==,type:comment]
#
#ENC[AES256_GCM,data:cqHRFyXmhSDRCrjmF5vCnKT2i+5Opkny4ELzfUTlRZwJLp1Ovy7Vw2V1SuXuDAZEgdfMRNrecCJfzFfm4/rm37ED9qv1fyLSECk=,iv:Gp0JV6xO1y1nOj2+fxo0rqKB1ZqOE+AGWK8clPOliHQ=,tag:OoMcw+cy3dWmOAAkpPaOfg==,type:comment]
#ENC[AES256_GCM,data:e1vErTZwq81Fsz++6dB0uYT45wsINki2X86HQRPTM60751DIbVS8,iv:Z77ku5Oms+ljxpX/GFmgsdAlUYA77E6JVSbOme97310=,tag:/ZSUyIo6K4fwTpl1I4JYYQ==,type:comment]
#
#ENC[AES256_GCM,data:wS9VsfTmYwzqPNhEBhZiBHKQJxJaNlHkP+4p91GmHtwywAi5wYkf+6LfBpWbg4PyDbA9QHx4hv8BAkS65kUCozRYHI5ozYCC5Lck,iv:+NSHlDYGw3YtJr284x2ASRquLl0p5yTCOIGOvXLuYvs=,tag:u6/B3hUR29ZOTNbsZP00YA==,type:comment]
#ENC[AES256_GCM,data:+GZgO+jNzAnKXR4MgoCUpxYLfpCg6o6vApIbWJIjZUH8bNFr5IxbJ50UF8gmd05jr8gsDWnp0al0XKVnU4R9TkSQACQ=,iv:Uaqpw6JwTJpVHojhi1MtI25bRmiP0xatoJNE9HTA5VE=,tag:GRnE6r8/g7v66Bxfb600iQ==,type:comment]
#ENC[AES256_GCM,data:27couUGn6ML6dCoPiD3O9SbfBZ5D3a19rwxWhHWflrVPXYeQ1ShZb08/Zh7agZEGYA==,iv:nMtfTUMHxyip4EN5s0tzRi1IaFgcclIdOSGfuLe3nvQ=,tag:c7j10GCcqjNLMl+no7zYOQ==,type:comment]
paper_rcon_password: ENC[AES256_GCM,data:DywDls4+OmLFhP5s,iv:VqPPxvGlsLF63KCVLfdz8Olsde4sO5byDyKOQk0Jdpo=,tag:dfvH3A4FNK52fpl76wElJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkN1hxcXFpbjRoaVBYNngy
            dGZGZiszc1krUnQ0UmlkaHVLYWw1VHpwMGpZCm0xaXEwdzBuRXVpT1Z2c1F4VFJa
            bzNjNzl2UVpheXNTQk5HazgvT25BSzgKLS0tIDVGYzlaenRtZmZrZHVQa1E0aHl6
            cDJQK3JCOWR6L0ZwSE01Q2ZNQThVekUKRDnCH25Xz/McGYBvk3asQuyQS97KpqIv
            wadmY8yJ37nNMXO/3zzP7txifB7j+RMGHLoSehblcq5vwLft0aTDyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n60xeumad6dxu59864v3dydp2jxj0nerlvtqf3y3gaaqh3ffnv5s7l39qn
    lastmodified: "2026-05-21T01:14:46Z"
    mac: ENC[AES256_GCM,data:lNP8yLYYJf7EeWKcQ6DZ4cIPsv2vU+LCBcTzI8ec+5db11ovp1JZ7rSRPqQw2gOfJS3KlB1006JdgEVrleC3uS5Cy+fbklJsH44fFipELG2YMuIABOiknFaI9Mt2Sjv17O24VvW9BbvZ2df/RTKIE6nm8dAYuhw201qyYHqZffM=,iv:9NKoFjaCsb8+ladCEorLcpzebSbatlhPXEMXeucf7dA=,tag:lNND2SfDO2fTWunm9bi3SQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
