tailscale_authkey: ENC[AES256_GCM,data:XTy/mHoZpXS40JRY0mem3oCPTZsOJs2l0JuZKEp0Dxi3L2wXfaqyS4+UL6YWcVAKUhEJEwIyvsml0jlDjg==,iv:U76B2MLL+NGg+kM7+EzOhWThWjZFkTCw0SPAgIGZSDc=,tag:u21otvQE0IWghozEkDlONA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2S0JBakc0N3l6THAySE5p
            YkFtTXpWMm94dGhRMytnM0ZrN0swR1dJQ0E4ClhqSWRFemt3bG83SkVnYnM5aDRG
            NmZFQXZMUlk2WkdZVndpRjh1ajhhRVEKLS0tIGtwdGVuUXRJSnZWaVJqdXNZQk10
            dmFTeit5QTZTdU9sNlhmeUpqMWJNazAKANS3IX7Y+lq9qli1ELjoPo5dl1NRECJT
            tk2W5o7K6FHSmZbg2r8Gd93ayE4qB42LNidzTtTt+6Vky8E2Qa4gqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n60xeumad6dxu59864v3dydp2jxj0nerlvtqf3y3gaaqh3ffnv5s7l39qn
    lastmodified: "2026-05-28T00:29:16Z"
    mac: ENC[AES256_GCM,data:fOvAM2KLijkT+J3QGt0oh3omXKTDZHi7LGcvW52MZJVcqpNRaeN4I2u/yYk7F5EnmNaofUpd6m+qFgZFUfahmPdlEj6/kq6M9vBYMYxANhae6roxeA0y38Vkn+4jW3Z9krK14texFrltpZw9Wh8ByNn8cHrq1N1FQDXEvBc+ojo=,iv:lr/HtBGmie/7X1K8KnnVaNDtNdRX0VfFAK9hHm/xGUs=,tag:52bPLB05i+jBFu6Ku2Cbbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
