#ENC[AES256_GCM,data:YxcWyeL5PucAXSSCuT4WfTQlWOGoaA+bRdapXFHgU0a95EtHB/MvtBrRN7NehXRSFU0jHFwt1qkEOWR53otj+1g=,iv:URMx90C5PIEQMxDmJTlfSdQlb6smMyBWZxr2AbDAuls=,tag:+YMTatm7xBgssjV5AP9npQ==,type:comment]
#ENC[AES256_GCM,data:oDwA2YF2uoIWlPAAl9lxyfUkAdtLQiQsdPkWovbZW6o9wUzOE154ZrU+9M0YMqjZMahSfCnJYAzWfAyhjFAuWHipOerbJlvbHQ+D,iv:OteFhwxKxSBN5jNs86dd/PmrYNHZkuaI/+4FDqTgtLc=,tag:OZSLSRDBk99+eiAxrqfddQ==,type:comment]
#ENC[AES256_GCM,data:7s1m42+5W1OitKBJfef6iccty9Z+L01PGm1qcneT19DaCOLD3d5sXw7rzm/T40brO8Yb+WQE10Lh3JMG3qCICa4=,iv:WdYQ3xMyeuafXdf5k9gpsjhe9nnXKR2slgLWzFaEiAA=,tag:f5z4F8zNmQGshnykUc6kCA==,type:comment]
#ENC[AES256_GCM,data:rEGsyKRLJkMcUrRQHE9Lllnn2uPy8E/6Y3KPv1uY0dfIPlsGIp1SiKO3qCjas+KqsJzi91kgNyAamEPXkvoB1K3L7V2VARqj5Vu5PFL4,iv:RXcIqVIJ2/y5wwkBcHvjeZzn+bXJYwoeSiNzX7FYbTs=,tag:n5npnLnyBVeeQwF5652sKg==,type:comment]
pseudo_rdp_password: ENC[AES256_GCM,data:xbhxk2tGeaHDaEzmGYflf0DR,iv:yPCxQ+AaNcuOki4U0P71JaUKdrUJI3YUXxFuRNDbWJA=,tag:mXdeoKCm+hpICrHNIyxixQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWjZRa005TVhEMUVHWGww
            UWcrb05CVzIwZGRZRjhLSXZRZUI1LzdUNVNJCjNPZFYzV1p5TXloclIranFtRUNX
            QjQvYU9wVXlyQWFteG5EOUtzRXJuOW8KLS0tIDFWbkZOeFhKQ3c1K3pHL1lFQTJh
            TlB5T0toeHBpSXdscG5Rd01QU0VCejgKxgnrllXkyb1jWHOUwzWgCs5RVJuHtWpS
            oJcwh9N6vvmVEBHknAY3QAwM5kGbo5CQSSyQFlq5vWpoT6/CDOPH5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n60xeumad6dxu59864v3dydp2jxj0nerlvtqf3y3gaaqh3ffnv5s7l39qn
    lastmodified: "2026-06-20T19:49:32Z"
    mac: ENC[AES256_GCM,data:1lusAAiRzZk4NrYP3Xk4k1c39ldVd7GKgnfr3xi+xbrEugT9yyeWut6VHfxh7dKZcJsnLdmxupqfBSt7QSCHAbeJuRB9B3cqXXnbQRFvLd5Di6i5e2XYtmtkDqQUGyZHzy/hyo8VXEcQ6x6GyaCDKHYsPl5fWs6F5zXEso1fWwI=,iv:yaNuyxNR8dMk1rXUpKdz9YuF17eKUvLZ9PiuMAqrkRE=,tag:yw4tc+yAWtK7uZOieJj1LA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
