#ENC[AES256_GCM,data:YxcWyeL5PucAXSSCuT4WfTQlWOGoaA+bRdapXFHgU0a95EtHB/MvtBrRN7NehXRSFU0jHFwt1qkEOWR53otj+1g=,iv:URMx90C5PIEQMxDmJTlfSdQlb6smMyBWZxr2AbDAuls=,tag:+YMTatm7xBgssjV5AP9npQ==,type:comment]
#ENC[AES256_GCM,data:oDwA2YF2uoIWlPAAl9lxyfUkAdtLQiQsdPkWovbZW6o9wUzOE154ZrU+9M0YMqjZMahSfCnJYAzWfAyhjFAuWHipOerbJlvbHQ+D,iv:OteFhwxKxSBN5jNs86dd/PmrYNHZkuaI/+4FDqTgtLc=,tag:OZSLSRDBk99+eiAxrqfddQ==,type:comment]
#ENC[AES256_GCM,data:7s1m42+5W1OitKBJfef6iccty9Z+L01PGm1qcneT19DaCOLD3d5sXw7rzm/T40brO8Yb+WQE10Lh3JMG3qCICa4=,iv:WdYQ3xMyeuafXdf5k9gpsjhe9nnXKR2slgLWzFaEiAA=,tag:f5z4F8zNmQGshnykUc6kCA==,type:comment]
#ENC[AES256_GCM,data:rEGsyKRLJkMcUrRQHE9Lllnn2uPy8E/6Y3KPv1uY0dfIPlsGIp1SiKO3qCjas+KqsJzi91kgNyAamEPXkvoB1K3L7V2VARqj5Vu5PFL4,iv:RXcIqVIJ2/y5wwkBcHvjeZzn+bXJYwoeSiNzX7FYbTs=,tag:n5npnLnyBVeeQwF5652sKg==,type:comment]
pseudo_rdp_password: ENC[AES256_GCM,data:EEzCA3GqIlgiPNDC,iv:gsOiJxuEnn1qt56B7Diw4IT932XxKnuNzyoCc6X50aI=,tag:+eKiPg9YoZzaXTpeDhzDxQ==,type:str]
steam_account_name: ENC[AES256_GCM,data:SRQ+HudDilwxkw==,iv:6hVvXXF8tsQHs3E06T+w0ldTQp7izTmC2E1Os5tQwjU=,tag:fe9jnSsKZv3dOZKiey0N4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWjZRa005TVhEMUVHWGww
            UWcrb05CVzIwZGRZRjhLSXZRZUI1LzdUNVNJCjNPZFYzV1p5TXloclIranFtRUNX
            QjQvYU9wVXlyQWFteG5EOUtzRXJuOW8KLS0tIDFWbkZOeFhKQ3c1K3pHL1lFQTJh
            TlB5T0toeHBpSXdscG5Rd01QU0VCejgKxgnrllXkyb1jWHOUwzWgCs5RVJuHtWpS
            oJcwh9N6vvmVEBHknAY3QAwM5kGbo5CQSSyQFlq5vWpoT6/CDOPH5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n60xeumad6dxu59864v3dydp2jxj0nerlvtqf3y3gaaqh3ffnv5s7l39qn
    lastmodified: "2026-07-02T00:23:26Z"
    mac: ENC[AES256_GCM,data:NlmwNLtiLm837lKgXBgc+hFqMRGUU/540prIMIAuoozmJzq7SHRHRAHV+YIpauCX07+v5TQ5cne46RNrvN0wKhoNvnWEUiwsQpK1b6cGu61anfaRDuw44J+3Z8OF3YG3GXzZOA9Z5qaZTn0ev0xQIHFZ4yVfa+ATydMBBCgp92I=,iv:59UgmPjEUSx4Q22wGBI2IZi/cJKDV2/TCWgsAf26KOI=,tag:OjYtj3oBktZPsE9Pyvgqpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
